### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 

## Simple Keras 모델 생성/학습 - AND Function

In [18]:
# 1. Numpy 가져오기
import numpy as np

print(np.__version__)

1.18.5


In [19]:
# 2. 입력/출력 데이터 만들기
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])
X,Y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [20]:
# 3. Keras 패키지 가져오기
from tensorflow import keras
from tensorflow.keras import layers

print(keras.__version__)

2.4.0


In [30]:
# 4. Perceptron 모델 생성
model = keras.Sequential()

#네트워크 쌓기
model.add(layers.Dense(units=1, input_dim=2))
model.add(layers.Activation('sigmoid'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 1)                 3         
_________________________________________________________________
activation_11 (Activation)   (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [31]:
# 5. Compile - Optimizer, Loss function 설정

sgd = keras.optimizers.SGD(lr=0.1)
model.compile(loss='binary_crossentropy',
                    optimizer='sgd') 

In [32]:
# 6. 학습시키기
model.fit(X,Y,
        batch_size=1 ,        # 문제 몇개를 풀고 답을 확인 할 것인가?  문제 푸는갯수에 따라 속도 가달라짐
        epochs= 500)            #반복횟수 

===================] - 0s 789us/step - loss: 0.4287
Epoch 257/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4282
Epoch 258/500
4/4 [==============================] - 0s 790us/step - loss: 0.4277
Epoch 259/500
4/4 [==============================] - 0s 1ms/step - loss: 0.4273
Epoch 260/500
4/4 [==============================] - 0s 797us/step - loss: 0.4268
Epoch 261/500
4/4 [==============================] - 0s 873us/step - loss: 0.4264
Epoch 262/500
4/4 [==============================] - 0s 800us/step - loss: 0.4260
Epoch 263/500
4/4 [==============================] - 0s 789us/step - loss: 0.4255
Epoch 264/500
4/4 [==============================] - 0s 797us/step - loss: 0.4251
Epoch 265/500
4/4 [==============================] - 0s 855us/step - loss: 0.4246
Epoch 266/500
4/4 [==============================] - 0s 840us/step - loss: 0.4242
Epoch 267/500
4/4 [==============================] - 0s 821us/step - loss: 0.4237
Epoch 268/500
4/4 [==============================]

In [33]:
# 7. 모델 테스트하기
test_data = np.array([[0,1],[1,1],[0,0],[1,0]]) 
result = model.predict(test_data)

print(result)

[[0.32034743]
 [0.5536421 ]
 [0.10777907]
 [0.24120994]]


In [ ]:
# 예측
# print(model.predict_classes(test_data)) 구형 코드 

print(model.predict_classes(test_data) > 0.5)