### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 

## Simple Keras 모델 생성/학습 - XOR Function

In [11]:
# 1. Numpy 가져오기

import numpy as np

print(np.__version__)

1.18.5


In [12]:
# 2. 입력/출력 데이터 만들기
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [13]:
# 3. Keras 패키지 가져오기

from tensorflow import keras
from tensorflow.keras import layers

print(keras.__version__)


2.4.0


In [14]:
# 4. MLP 모델 생성
model = keras.Sequential()
model.add(layers.Dense(units=8, input_dim=2))
model.add(layers.Activation('relu'))
model.add(layers.Dense(1))
model.add(layers.Activation('sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 24        
_________________________________________________________________
activation_2 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 5. Compile - Optimizer, Loss function 설정
sgd = keras.optimizers.SGD(lr = 0.1)
model.compile(loss='binary_crossentropy', 
            optimizer=sgd,
            metrics=['accuracy'])

In [17]:
# 6. 학습시키기
model.fit(X,y,
        batch_size=1 ,
        epochs= 500) 

0
Epoch 299/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0254 - accuracy: 1.0000
Epoch 300/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0252 - accuracy: 1.0000
Epoch 301/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0250 - accuracy: 1.0000
Epoch 302/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0248 - accuracy: 1.0000
Epoch 303/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0247 - accuracy: 1.0000
Epoch 304/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0244 - accuracy: 1.0000
Epoch 305/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0245 - accuracy: 1.0000
Epoch 306/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0243 - accuracy: 1.0000
Epoch 307/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0242 - accuracy: 1.0000
Epoch 308/500
4/4 [==============================] - 0s 1ms/step - loss: 0.0240 - accuracy: 1.0000
Epoch 30

In [18]:
# 7. 모델 테스트하기
test_data = np.array([[0,1],[1,1],[0,0],[1,0]]) # 1 0 0 1
result = model.predict(test_data)

print(result)

[[0.99678504]
 [0.00333278]
 [0.03279821]
 [0.99407285]]


In [19]:
print(model.predict_classes(test_data) > 0.5)


[[ True]
 [False]
 [False]
 [ True]]


In [20]:
model.get_weights()

[array([[-1.0577197 , -2.6142387 , -0.384258  , -0.09024042,  2.729299  ,
          1.4150066 , -0.64423436, -0.38368753],
        [ 1.0595119 ,  2.618738  , -0.35073373, -0.4799985 , -1.6731786 ,
          2.0358052 , -0.5649603 , -0.56277424]], dtype=float32),
 array([-0.00259786, -0.00651211,  0.        ,  0.        , -0.0059021 ,
        -1.4167404 ,  0.        ,  0.        ], dtype=float32),
 array([[ 1.4110395],
        [ 3.572735 ],
        [-0.7413104],
        [ 0.4197787],
        [ 3.123412 ],
        [-2.7515469],
        [-0.5198914],
        [ 0.5421518]], dtype=float32),
 array([-3.3840332], dtype=float32)]